[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/transactions"
  to = "/.netlify/functions/transactions"
  status = 200

[[redirects]]
  from = "/api/groups/*"
  to = "/.netlify/functions/groups/:splat"
  status = 200

[[redirects]]
  from = "/api/group-members"
  to = "/.netlify/functions/group-members"
  status = 200

[[redirects]]
  from = "/api/invitations/*"
  to = "/.netlify/functions/invitations/:splat"
  status = 200

[[redirects]]
  from = "/api/balances"
  to = "/.netlify/functions/balances"
  status = 200

